name: run-tests
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  run-tests:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: run tests
        run: env
