name: run-tests
on:
  pull_request_review:
    types:
      - submitted
jobs:
  run-tests:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    if: github.event.pull_request.base.ref == 'main' && github.event.review.state == 'APPROVED'
    steps:
      - name: run tests
        env:
          MY_REVIEW: ${{ github.event.review }}
          MY_PR: ${{ github.event.pull_request }}
        run: echo "$MY_REVIEW \n\n $MY_PR"
