name: run-tests
on:
  pull_request:
    types:
      - labeled
jobs:
  run-tests:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    if: github.event.label.name == 'ready for testing'
    steps:
      - name: run tests
        env:
          MY_REVIEW: ${{ toJson(github.event.review) }}
          MY_PR: ${{ toJson(github.event.pull_request) }}
        run: echo "$MY_REVIEW \n\n $MY_PR"
